apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "courtmate-ui.fullname" . }}
  labels:
    app: {{ include "courtmate-ui.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "courtmate-ui.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "courtmate-ui.name" . }}
    spec:
      containers:
        - name: courtmate-ui
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if .Values.envFromSecret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret.secretName }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
