apiVersion: v1
kind: Service
metadata:
  name: {{ include "courtmate-ui.fullname" . }}
  labels:
    app: {{ include "courtmate-ui.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "courtmate-ui.name" . }}
